### ISSUE TITLE
Issues with account expiration dates

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#497]
Adldap2 Version: 7.0.15
LDAP Type: Active Directory
PHP Version: 7.0.9

### Description:
Hi, I have 4 types of users:

- User which does not expire
- User which not expired yet, but have and expiration date
- User expired
- User which does not expire, but with and expiration date set to 31/12/9999 (do not ask why.. 🤦‍♂️)

These are the values retrieved from AD:
![image](https://user-images.githubusercontent.com/6285255/35807869-5665ffc6-0a84-11e8-84f6-4b85ad92dc15.png)

In the last user, if I try to get the `isExpired()` status or the date with `expirationDate()`, I get the following exception:
![image](https://user-images.githubusercontent.com/6285255/35807996-b5dc4d84-0a84-11e8-902b-5b3a44e8ba08.png)

**Comment by stevebauman** [comment]
Hi @Albvadi, looking into this now, thanks!

**Comment by stevebauman** [comment]
Hey @Albvadi, are you perhaps using the 32-bit version of PHP?

**Comment by Albvadi** [comment]
Yes, exactly: `PHP 7.0.9 (cli) (built: Jul 20 2016 11:08:23) ( ZTS )`
It´s a Xampp version, ApacheFriends XAMPP Version 7.0.9, and I think all xampp versions are 32-bit..

Is this the problem??

**Comment by stevebauman** [comment]
It's not a problem, it just explains why my tests pass locally, and on travis, but the method fails in your environment:

https://github.com/Adldap2/Adldap2/blob/master/tests/Models/UserTest.php#L183-L194

I'm going to test on 32-bit and see if I reproduce this.

**Comment by Albvadi** [comment]
I´m using it in Laravel, but posted here because it´s a method not related with Laravel...

But, in the screenshot, the dump show the parameters and in the second, the value has a dot making a decimal value... maybe it´s a problem with Laravel and the requests??

**Comment by stevebauman** [comment]
It's not an issue of requests, it's definitely the 32-bit version of PHP:

http://php.net/manual/en/language.types.integer.php#language.types.integer.overflow

> If PHP encounters a number beyond the bounds of the integer type, **it will be interpreted as a float instead.**

I'll see if I can patch this for 32-bit versions, thanks @Albvadi!

**Comment by Albvadi** [comment]
> I'll see if I can patch this for 32-bit versions

That would be great!
Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi, I believe this was resolved with the following `date()` method here:

https://github.com/Adldap2/Adldap2/blob/85740a36638a89ac32b3e6c73a7f073573409c91/src/Models/User.php#L1212-L1214

Can you verify by using the latest release?

**Comment by Albvadi** [comment]
I´ll try it as soon as possible.

**Comment by Albvadi** [comment]
Sorry, but the problem persist.
Really the code is the same.
```php
$date = date($this->dateFormat, $unixTime); 
return new DateTime($date);
```
is the same than 
```php
return new DateTime(date($this->dateFormat, $unixTime));
```

The message error and the trace are the same than the original post.

**Comment by Albvadi** [comment]
ping @stevebauman 

Hi,
a long time ago, I migrated to a 64bit PHP version and now, when I have taken up the modifications that involve using the expiration date, everything works as expected with the 64 bit version.

Perhaps, you want to close this issue because you do not support such old versions or because in LdapRecord you manage the dates differently and this does not happen. Its your choice.

I take this opportunity to thank you for the new projects you have in progress (LdapRecord, Scout (or Watchdog), etc ...).
You make life very easy for other mortals ... I hope I can use them soon .. 😉
